spring:
  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only


  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  jpa:
    properties:
      hibernate:
        default_schema: public


server:
  port: 9999


