spring:
  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only



  jpa:
    properties:
      hibernate:
        default_schema: public


server:
  port: 9999


