name: citronix
services:

  postgres:
    image: postgres:17
    container_name: citronix-postgres
    environment:
      POSTGRES_DB: citronix
      POSTGRES_USER: citronix
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local